source 'https://rubygems.org'
ruby '1.9.3'

gem 'rails', '~> 3.2'
gem 'mysql2'

gem 'pg'
gem 'heroku'
gem 'sidekiq'
gem 'slim', '<= 1.3.0'
gem 'sinatra', require: nil
gem 'colored'
gem 'bitly'
gem 'stripe', git: 'git://github.com/stripe/stripe-ruby.git'
gem 'meta_search', '>= 1.1.0.pre'
gem 'activeadmin'
gem 'omniauth'
gem 'omniauth-facebook', git: 'git://github.com/mkdynamic/omniauth-facebook.git'
gem 'encrypted-cookies'
gem 'koala'
gem 'cancan'
gem 'garails'
gem 'gabba'
gem 'newrelic_rpm'
gem 'aws-sdk'
gem 'paperclip'
gem 'fastercsv'
gem 'json'
gem 'impressionist'
gem 'simple_form', '~> 2.0'
gem 'juggernaut', git: 'git://github.com/FewKinG/juggernaut.git'
gem 'simple_uuid'
gem 'whenever', require: false
gem 'validates_timeliness', '~> 3.0'

group :assets do
  gem 'coffee-rails', '~> 3.2.1'
  gem 'uglifier', '>= 1.0.3'
  gem 'font-awesome-sass-rails'
end

gem 'therubyracer', platforms: :ruby
gem 'less-rails'
gem 'autoprefixer-rails'
gem 'semantic-ui-rails'
gem 'haml-rails'
gem 'sass-rails', '~> 3.2.3'
gem 'compass-rails'
gem 'bootstrap-sass', '~> 2.0.1'
gem 'ui_datepicker-rails3'

group :development, :test do
  gem 'awesome_print'
  gem 'hirb'
  gem 'interactive_editor'
  gem 'pry', '0.9.10'
  gem 'pry-rails'
  gem 'pry-coolline'
  gem 'erb2haml'
  gem 'seed_dump'
  gem 'quiet_assets'
  gem 'magic_encoding'
  gem 'better_errors'
  gem 'binding_of_caller'
  gem 'rubygems-bundler'
  gem 'thin'
  gem 'foreman'
  gem 'dotenv-rails'
end
