source 'http://rubygems.org'

gem 'rails', '3.2.11'
gem 'mysql2', '~> 0.3.10'

gem 'pg'
gem 'thin'
gem 'foreman'
gem 'heroku'
gem 'sidekiq'
gem 'slim', '<= 1.3.0'
gem 'sinatra', require: nil
gem 'colored'
gem 'bitly'
gem 'stripe', git: 'https://github.com/stripe/stripe-ruby'
gem 'sourceninja', '~> 0.9.0'
gem 'meta_search', '>= 1.1.0.pre'
gem 'activeadmin'
gem 'omniauth'
gem 'omniauth-facebook', git: 'git://github.com/mkdynamic/omniauth-facebook.git'
gem 'encrypted-cookies'
gem 'koala'
gem 'cancan'
gem 'garails'
gem 'gabba'
gem 'newrelic_rpm'
gem 'aws-sdk'
gem 'paperclip'
gem 'fastercsv'
gem 'json'
gem 'impressionist'
gem 'simple_form', '~> 2.0'
gem 'juggernaut', git: 'git://github.com/FewKinG/juggernaut.git'
gem 'simple_uuid'
gem 'whenever', require: false
gem 'validates_timeliness', '~> 3.0'
gem 'dotenv-rails'

group :assets do
  gem 'coffee-rails', '~> 3.2.1'
  gem 'uglifier', '>= 1.0.3'
  gem 'font-awesome-sass-rails'
end

gem 'haml-rails'
gem 'sass-rails', '~> 3.2.3'
gem 'compass-rails'
gem 'bootstrap-sass', '~> 2.0.1'
gem 'jquery-rails'
gem 'ui_datepicker-rails3'

group :development do
  gem 'logging-rails', require: 'logging/rails'
  gem 'awesome_print'
  gem 'pry'
  gem 'erb2haml'
  gem 'seed_dump'
  gem 'magic_encoding'
  gem 'nifty-generators'
  gem 'rails_best_practices'
  gem 'wirble'
  gem 'hirb'
  gem 'itslog'
  gem 'ruby_parser'
  gem 'hpricot'
  gem 'letters'
  gem 'better_errors'
  gem 'binding_of_caller'
end
