source 'https://rubygems.org'
ruby '1.9.3'

gem 'active_link_to'
gem 'activeadmin'
gem 'aws-sdk'
gem 'bitly'
gem 'cancan'
gem 'colored'
gem 'encrypted-cookies'
gem 'fastercsv'
gem 'gabba'
gem 'garails'
gem 'heroku'
gem 'impressionist'
gem 'json'
gem 'juggernaut', git: 'git://github.com/FewKinG/juggernaut.git'
gem 'koala'
gem 'leader', git: 'git://github.com/halo/leader.git'
gem 'meta_search', '>= 1.1.0.pre'
gem 'mysql2'
gem 'newrelic_rpm'
gem 'omniauth'
gem 'omniauth-facebook', git: 'git://github.com/mkdynamic/omniauth-facebook.git'
gem 'paperclip'
gem 'pg'
gem 'rails', '~> 3.2'
gem 'sidekiq'
gem 'simple_form', '~> 2.0'
gem 'simple_uuid'
gem 'sinatra', require: nil
gem 'slim', '<= 1.3.0'
gem 'stripe-rails'
gem 'stripe_tester'
gem 'validates_timeliness', '~> 3.0'
gem 'whenever', require: false

group :assets do
  gem 'coffee-rails', '~> 3.2.1'
  gem 'font-awesome-sass-rails'
  gem 'uglifier', '>= 1.0.3'
end

gem 'autoprefixer-rails'
gem 'bourbon'
gem 'haml-rails'
gem 'less-rails'
gem 'sass-rails', '~> 3.2.3'
gem 'semantic-ui-rails'
gem 'therubyracer', platforms: :ruby
gem 'ui_datepicker-rails3'

group :development, :test do
  gem 'awesome_print'
  gem 'better_errors'
  gem 'binding_of_caller'
  gem 'dotenv-rails'
  gem 'erb2haml'
  gem 'foreman'
  gem 'hirb'
  gem 'interactive_editor'
  gem 'magic_encoding'
  gem 'pry', '0.9.10'
  gem 'pry-coolline'
  gem 'pry-rails'
  gem 'quiet_assets'
  gem 'rubygems-bundler'
  gem 'seed_dump'
  gem 'thin'
end
