package_assets: on
embed_assets: datauri
compress_assets: on
css_compressor_options:
  line_break: 0

javascripts:
  common:
    - public/javascripts/jquery.min.js
    - public/javascripts/jquery-ui.min.js
    - public/javascripts/jquery_ujs.js
    - public/javascripts/common.js
  vendor:
    - public/javascripts/vendor/*.js
  welcome:
    - public/javascripts/welcome.js
  app:
    - public/javascripts/application.js

stylesheets:
  bootstrap:
    - public/stylesheets/bootstrap/bootstrap.css
  common:
    - public/stylesheets/common.css
  vendor:
    - public/stylesheets/vendor/tipsy.css
  welcome:
    - public/stylesheets/welcome.css
  app:
    - public/stylesheets/application.css
    - public/stylesheets/dashboard.css
