package_assets: on
embed_assets: datauri
compress_assets: on
css_compressor_options:
  line_break: 0

javascripts:
  app:
    - public/javascripts/jquery.min.js
    - public/javascripts/jquery-ui.min.js
    - public/javascripts/jquery-ui-timepicker-addon.js
    - public/javascripts/rails.js
    - public/javascripts/application.js
stylesheets:
  app:
    - public/stylesheets/defaults.css
    - public/stylesheets/application.css
    - public/stylesheets/buttons.css
    - public/stylesheets/flash.css
    - public/stylesheets/auth.css
    - public/stylesheets/users.css
    - public/stylesheets/smoothness/smoothness.css