embed_assets: on

javascripts:
  app:
    - public/javascripts/jquery.min.js
    - public/javascripts/application.js
stylesheets:
  app:
    - public/stylesheets/defaults.css
    - public/stylesheets/application.css
    - public/stylesheets/buttons.css
    - public/stylesheets/flash.css
    - public/stylesheets/auth.css
    - public/stylesheets/users.css