common: &common
  adapter: mysql2
  encoding: utf8
  reconnect: false
  pool: 5
  username: root
  password: sonymac
  socket: /tmp/mysql.sock

development:
  <<: *common
  database: SGA_development

test:
  <<: *common
  database: SGA_test

production:
  <<: *common
  database: SGA_production
