FB_APP_ID ||= ENV["FB_APP_ID"]
FB_APP_SECRET ||= ENV["FB_APP_SECRET"]
FB_APP_KEY ||= ENV["FB_APP_KEY"]

development:
  app_id: FB_APP_ID
  secret_key: FB_APP_SECRET
  oauth_key: FB_APP_KEY
test:
  app_id: FB_APP_ID
  secret_key: FB_APP_SECRET
  oauth_key: FB_APP_KEY
production:
  app_id: FB_APP_ID
  secret_key: FB_APP_SECRET
  oauth_key: FB_APP_KEY