development:
  app_id: ENV["FB_APP_ID"]
  secret_key: ENV["FB_APP_SECRET"]
  oauth_key: ENV["FB_APP_KEY"]
test:
  app_id: ENV["FB_APP_ID"]
  secret_key: ENV["FB_APP_SECRET"]
  oauth_key: ENV["FB_APP_KEY"]
production:
  app_id: ENV["FB_APP_ID"]
  secret_key: ENV["FB_APP_SECRET"]
  oauth_key: ENV["FB_APP_KEY"]