# Create SubscriptionPlans

SubscriptionPlan.free_trial
SubscriptionPlan.single_page_monthly
SubscriptionPlan.single_page_yearly
SubscriptionPlan.multi_page_monthly
SubscriptionPlan.multi_page_yearly
